### ISSUE TITLE
Problems with Tail Auto-Rig

### ISSUE THREAD

**Issue by andreastanner** [RxLaboratory/Duik#1004]
Hi Nicolas

I used the tail bones very often but i noticed, that sometimes the rig get's very broken after auto-rig... 

What am I doing: 

1. Make puppet pins
2. Use the "add pin" function to make the blue pins
3. "CTRL" + click on the tail bone button, it's automatically connected
4. Auto-Rig
5. The bones get broken, but the pins stay at position. But if i use the tail tip controller, it's behaving very odd...

By the way: it also happens when just making a 5 bone tail bone chain, shape (move the bones) the it a bit and then auto-rig.

Do you have an idea? Is it a bug or am I doing something wrong?

Thanks a lot!
![Untitled-1](https://user-images.githubusercontent.com/55541491/216550325-d4447e15-b030-40ab-8287-8a9cc71d125d.jpg)

**Comment by Nico-Duduf** [comment]
Strange; can you send me the project?

Note that it may be that the bone just look wrong but work correctly anyway. That happens with the spines too, Duik has to reset the rotation of the bones and this leads to them being visually offset like this, but working correctly anyway. If that's the case here too, what I need to do is to reset their apearance correctly after the rig's been done

**Comment by Nico-Duduf** [comment]
Oh I've just understood: you've set the autorig to use the Bézier IK instead of FK for rigging "long chains".
That doesn't work properly on "complex" shapes like this.
The best way to achieve this is to rig the tail on a straight line, and then use the controllers to get the shape you'd like. Or use FK ;)

This will be explained in the doc!

**Comment by andreastanner** [comment]
sorry very much that i didn't reply... had a lot to do ;). okay, thanks for this tipp. I guess i make it like you suggested next time!

**Comment by andreastanner** [comment]
I didn't choose FK because i can't get automatic movement when for example the torso is moved. This works only with the tail function and a cleaner on the position (like i saw on your robot tutorial). If i choose FK, only rotation affects the tail, right?

**Comment by Nico-Duduf** [comment]
Yes you're right for the FK

Actually in this case, the better would be to draw a mask around the tail/flower so when you add puppet pins, the mesh uses the mask instead of the alpha.
This way you can just add a few puppets pins and they can be aligned on a straight line, and the IK rig will work correctly. The bones don't necessarily have to be aligned to the branch/tail in this case

**Comment by andreastanner** [comment]
aah nice, this is a good solution ;), thanks!! Try it when rigging the next shot.
