### ISSUE TITLE
Extract controller doesn't work on AE2023

### ISSUE THREAD

**Issue by Dineshjaya** [RxLaboratory/Duik#1048]
Im Rookie sir ,,

I SET CONTROLLER in precomp then i switch into Maincomp to extract controller But Nothing Happened in there ( it's popped and nothing to shown )

HERE is THE LINK . PLS WATCH ( https://www.youtube.com/watch?v=xvWv3bdKM4k )

https://user-images.githubusercontent.com/128628905/228131672-63a7456d-6004-4b4b-84df-c28d993f9d2d.mp4

**Comment by jsaidler** [comment]
Updating After Effects from 23.1 to 23.3 solved te issue for me.

**Comment by Nico-Duduf** [comment]
We can't reproduce the issue here, on 23.3/Duik 17.0.4

If anyone still has the problem, can you:

- Make sure you're running the latest AE 23.3 and try again
- Reinit the preferences of After Effects and try again (move away your current prefs files, you can restore them later if you wish; go to preferences/general/ reveal preferences in explorer/finder)
- If it still doesn't work, activate Duik's dev & debug mode (Duik settings/switch "normal mode" to "dev & debug) and try again, and take a screenshot of any error and post it here
- if during previous step you didn't see any error message, do the same but with AE's javascript debugging (preferences/scripting & expressions/enable javascript debugger).

Also, a list of installed scripts and extensions may be useful, there may be a conflict somewhere 🤔

**Comment by urekmazino00** [comment]
This issue was previously noticed by many users who are using After Effects version 23.0. It happens in Duik Bassel and Duik Angela, and the problem is from that version of After Effects.

**Comment by Dineshjaya** [comment]
Hello Admin ..

Sorry for my English...

I Update Duik Today , after that i export controller from precomp to Main comp ,it's Working good ( after i export that ik Not working )

FK only Worked ( Could you Check With this Link )

I Want Reverse Action .. What can i do for That , Could you Solve My Problem.


https://github.com/RxLaboratory/Duik/assets/128628905/a067f02d-bcc2-4767-9c31-dacb693fc0b8
