### ISSUE TITLE
Kleaner on path problem

### ISSUE THREAD

**Issue by Jissse** [RxLaboratory/Duik#1227]
**Description**

Add kleaner on an animted path, error:

![image](https://github.com/user-attachments/assets/e60cabef-54e7-4945-b549-02f92ff3a177)

plzfixkthxbye

**Comment by ilyasok** [comment]
Usually, you don't use kleaner on paths. The workaround is to use key morph or a slider and then use kleaner on the slider. 

Tried fixing this bug with hardcoding the missing function (see below), and a new one risen (see the pic)
```
function isPath(prop){
    if (prop.matchName == "ADBE Vector Shape - Group") return true;
    if (prop.matchName == "ADBE Mask Atom") return true;
    return false;
}
```
![image](https://github.com/user-attachments/assets/759014b8-1ec1-49f6-a77a-58015f25cc18)

**Comment by Nico-Duduf** [comment]
I've finally had a look at this: the Kleaner just can't work on path properties (they're missing needed functions like `velocityAtTime`) ; if you need to use it on a path, just add Duik Pins on the path first, this works well.

I *could* make it so that Duik automatically adds the pins and the kleaner on the pins, but I'm not sure that's a good idea ;)

I'm just adding a warning if there's a path property in the selection when using the Kleaner, and some info about this in the doc.

Thanks for all your feedback
