### ISSUE TITLE
Copy/Paste Keyframes not working on layers with multiple paths and merge paths

### ISSUE THREAD

**Issue by woozygoozy** [RxLaboratory/Duik#837]
**Describe the bug**
I am trying to use copy paste keyframes commands and when I have a layer with multiple paths (and merge paths) DUIK is not copying the second path's keyframes....

*

https://user-images.githubusercontent.com/44062706/123682522-1602db00-d819-11eb-845d-271f1fc34d24.mp4

**Comment by Nico-Duduf** [comment]
I'm sorry to reply late! Thanks for your feedback, I'll fix this for Duik 17 available in a few weeks in Beta tests

**Comment by woozygoozy** [comment]
awesome! thanks!

**Comment by Nico-Duduf** [comment]
That being said I'll have a problem, I can't reproduce the bug here ^^

If you still have the project, can you send it?
Or can you try again, and if it fails try with the "Dev & Debug Mode" (you can set that in the settings of Duik), it should show some error which may be useful to understand what's going on

**Comment by woozygoozy** [comment]
I am not sure I have the project file any longer, but I will see if I can reproduce it again
